### ISSUE TITLE
Cannot read property 'setAttribute' of null

### ISSUE THREAD

**Issue by alexkendall** [slightlytyler/react-svgcon#1]
index.js:105 Uncaught TypeError: Cannot read property 'setAttribute' of null
    at SVGCon.normalize (index.js:105)
    at SVGCon.processSvg (index.js:94)
    at index.js:160

**Comment by slightlytyler** [comment]
@alexkendall are you passing a proper svg to the prop `svg`? Guessing that you're passing `svg` as `null`.

**Comment by slightlytyler** [comment]
Closing as I believe this is user error
